## fancy indexing
## Fancy indexing is like the simple indexing we've already seen, but we pass arrays of indices in place of single scalars

In [4]:
import numpy as np
rand = np.random.RandomState(42)

In [5]:
x = rand.randint(100, size=10)
print(x)

[51 92 14 71 60 20 82 86 74 74]


In [6]:
ind = [3, 7, 4]

In [7]:
x[ind]

array([71, 86, 60])

In [8]:
ind = np.array([[3, 7],
                [4, 5]])
x[ind]

array([[71, 86],
       [60, 20]])

## Fancy indexing also works in multiple dimensions

In [10]:
X = np.arange(12).reshape((3, 4))
X

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [11]:
row = np.array([0, 1, 2])
col = np.array([2, 1, 3])
X[row, col]

array([ 2,  5, 11])

In [12]:
X

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [14]:
X[[(0,2), (1,1), (2,3)]]

IndexError: too many indices for array